# vim: set ft=dockerfile ts=4 sw=4 et:
FROM alpine:latest
MAINTAINER @MAINTAINER@

# Install Supervisor
RUN apk --update upgrade -U && apk --no-cache add \
        supervisor

COPY supervisord.conf /etc/

RUN mkdir -p /var/log/supervisor

ENTRYPOINT [ "/usr/bin/supervisord" ]
