# vim: set ft=dockerfile ts=4 sw=4 et:
FROM @@USER@@/docker-alpine-core:3.18
MAINTAINER @@MAINTAINER@@

# Install PHP 8.1
RUN apk --update upgrade -U && apk --no-cache add \
        php81 \
        php81-ctype \
        php81-curl \
        php81-dom \
        php81-fileinfo \
        php81-fpm \
        php81-gd \
        php81-iconv \
        php81-intl \
        php81-json \
        php81-mbstring \
        php81-mysqli \
        php81-opcache \
        php81-openssl \
        php81-pcntl \
        php81-pdo \
        php81-pdo_mysql \
        php81-phar \
        php81-posix \
        php81-session \
        php81-tidy \
        php81-xml \
        php81-zip

# php-composer
ENV COMPOSER_PREFERRED 2
RUN wget -qO /tmp/composer-setup.php https://getcomposer.org/installer && \
    php /tmp/composer-setup.php --1 --install-dir=/usr/bin --filename=composer1 && \
    php /tmp/composer-setup.php --2 --install-dir=/usr/bin --filename=composer2 && \
    rm /tmp/composer-setup.php

COPY 00-prepare-php8.sh /etc/entrypoint.d/

# listen all interfaces
RUN sed -i -e 's|^listen =.*|listen = 9000|' /etc/php81/php-fpm.d/www.conf

# add php-fpm to supervisord
COPY supervisord.conf /etc/supervisor.d/php-fpm.conf
