# vim: set ft=dockerfile ts=4 sw=4 et:
FROM amery/docker-alpine-core:latest
MAINTAINER Alejandro Mery <amery@linux.com>

# Install MariaDB
RUN apk --update upgrade -U && apk --no-cache add \
        mariadb
