#!/bin/sh

set -eu

FILES=
IMAGES=
for df in $(find * -type f -name Dockerfile); do
	name="docker-$(echo ${df%/*} | tr '/' '-')"

	FILES="${FILES:+$FILES
}$name:$df"
	IMAGES="${IMAGES:+$IMAGES
}$name"
done

# sort
IMAGES="$(echo "$IMAGES" | sort -V)"
FILES="$(echo "$FILES" | sort -V)"

# generate list of managed images
cat <<EOT
# generated by $0
#
IMAGES =$(echo "$IMAGES" | sed -e 's/^/|\t$(PREFIX)/' | tr -d '\n' | sed -e 's/|/ \\\n/g')
EOT

for np in $FILES; do
	img="${np%:*}"
	df="${np#*:}"
	d="${df%/*}"

	from0=$(grep "^FROM" "$df" | head -n1 | sed -e 's/^FROM[ \t]\+//' -e 's/:.*//')
	from=
	for x in $IMAGES; do
		case "$from0" in
		*$x) from="$x" ;;
		esac

		[ -z "$from" ] || break
	done
	cat <<EOT
# $df
#
.PHONY: \$(PREFIX)$img
\$(PREFIX)$img: \$(B)/.$img

\$(B)/.$img:${from:+ \$(B)/.$from} $df
	\$(DOCKER) build \$(DOCKER_BUILD_OPT) -t \$(PREFIX)$img:latest $d/
	mkdir -p \$(@D)
	touch \$@
EOT
done
